In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [2]:
P = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [7]:
lambdas, V = np.linalg.eig(P)
V

array([[-0.9511379 ,  0.23863211,  0.1625802 ],
       [-0.12176309,  0.1923954 , -0.7705417 ],
       [-0.28374356,  0.95186067,  0.616306  ]], dtype=float32)

In [9]:
Lambdas = np.diag(lambdas)

In [10]:
Vinv = np.linalg.inv(V)

In [11]:
np.dot(V, np.dot(Lambdas, Vinv))

array([[25.000002 ,  2.       , -5.0000005],
       [ 3.0000002, -2.       ,  1.       ],
       [ 5.0000005,  7.0000005,  4.000001 ]], dtype=float32)

In [12]:
S = torch.tensor([[25, 2, -5], [2, -2, 1], [-5, 1, 4.]])
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [13]:
lambdas, Q = np.linalg.eig(S)

In [17]:
Lambdas = np.diag(lambdas)

In [18]:
np.dot(Q, np.dot(Lambdas, Q.T))

array([[25.000002 ,  2.       , -4.9999995],
       [ 2.       , -2.       ,  1.0000001],
       [-5.       ,  1.       ,  4.       ]], dtype=float32)