In [3]:
import numpy as np
import torch
import matplotlib.pyplot as plt

Let's calculate the pseudoinverse 𝐴+ of some matrix 𝐴 using the formula from the slides:

𝐴+=𝑉𝐷+𝑈𝑇

In [4]:
A_p = torch.tensor([[-1, 2], [3, -2], [5, 7.]])
A_p

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [5]:
U, d, VT = np.linalg.svd(A_p)

In [6]:
U

array([[ 0.12708324,  0.47409505,  0.8712541 ],
       [ 0.00164602, -0.87847555,  0.4777845 ],
       [ 0.99189067, -0.0592843 , -0.11241989]], dtype=float32)

In [7]:
d

array([8.669185 , 4.1042953], dtype=float32)

In [8]:
VT

array([[ 0.5579888 ,  0.82984847],
       [-0.82984847,  0.5579888 ]], dtype=float32)

In [14]:
D = np.diag(d)
D

array([[8.669185 , 0.       ],
       [0.       , 4.1042953]], dtype=float32)

In [15]:
Dinv = np.linalg.inv(D)

In [16]:
Dinv

array([[0.1153511 , 0.        ],
       [0.        , 0.24364719]], dtype=float32)

In [22]:
Dplus = np.concatenate((Dinv, np.array([[0, 0]]).T), axis=1)
Dplus

array([[0.1153511 , 0.        , 0.        ],
       [0.        , 0.24364719, 0.        ]])

In [27]:
PSUDO = np.dot(VT.T, np.dot(Dplus, U.T))
PSUDO

array([[-0.08767773,  0.17772513,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])

In [28]:
torch.pinverse(A_p)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])