In [30]:
import numpy as np
import torch
import matplotlib.pyplot as plt
from scipy.linalg import sqrtm

In [15]:
P = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

SVD and eigendecomposition are closely related to each other: 

* Left-singular vectors of $A$ = eigenvectors of $AA^T$.
* Right-singular vectors of $A$ = eigenvectors of $A^TA$.
* Non-zero singular values of $A$ = square roots of eigenvalues of $AA^T$ = square roots of eigenvalues of $A^TA$

**Exercise**: Using the matrix `P` from the preceding PyTorch exercises, demonstrate that these three SVD-eigendecomposition equations are true. 

As on slides, SVD of matrix 𝐴 is:

𝐴=𝑈𝐷𝑉𝑇

Where:

𝑈 is an orthogonal 𝑚×𝑚 matrix; its columns are the left-singular vectors of 𝐴.

𝑉 is an orthogonal 𝑛×𝑛 matrix; its columns are the right-singular vectors of 𝐴.

𝐷 is a diagonal 𝑚×𝑛 matrix; elements along its diagonal are the singular values of 𝐴.

In [16]:
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [17]:
U, d, VT = np.linalg.svd(P)

In [18]:
U

array([[-0.9757195 , -0.1822729 , -0.1214413 ],
       [-0.09750433, -0.1350092 ,  0.9860352 ],
       [-0.19612318,  0.9739348 ,  0.11395871]], dtype=float32)

In [19]:
d

array([26.163235,  8.187547,  2.539532], dtype=float32)

In [20]:
VT

array([[-0.98099935, -0.11960649,  0.15275636],
       [-0.01125803,  0.8211271 ,  0.5706343 ],
       [ 0.19368395, -0.55807215,  0.8068718 ]], dtype=float32)

In [21]:
D = np.diag(d)
D

array([[26.163235,  0.      ,  0.      ],
       [ 0.      ,  8.187547,  0.      ],
       [ 0.      ,  0.      ,  2.539532]], dtype=float32)

In [60]:
PPT = np.dot(P, P.T)
PPT

array([[654.,  66., 119.],
       [ 66.,  14.,   5.],
       [119.,   5.,  90.]], dtype=float32)

In [61]:
eig = np.linalg.eigvals(PPT)
eig

array([684.51483  ,  67.03592  ,   6.4492226], dtype=float32)

In [62]:
np.sqrt(eig)

array([26.163235,  8.187547,  2.539532], dtype=float32)